shorttitle:         Anıl Çetin'in Karalama Tahtası
title:              Anıl Çetin
email:              anilcetin@yandex.com
description:       >- 
  Kitap özetleri, notlar, ipuçları ve püf noktaları. 
author:             ANIL ÇETİN
baseurl:            ""
url:                ""
date_locale: tr
# Social Profiles
github_username:    actn
instagram_username: anilctn
linkedin_username:  anilctn

months:
    - Ocak
    - Şubat
    - Mart
    - Nisan
    - Mayıs
    - Haziran
    - Temmuz
    - Ağustos
    - Eylül
    - Ekim
    - Kasım
    - Aralık

# Add your google-analytics ID here to activate google analytics
#google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
